random_seed: 42
data:
  image_folder: "/home/ilyabushmakin/Documents/Projects/DataStorage/kaggle_personal/ProjectDINODataset/images"
  batch_size: 4
  num_workers: 5
model:
  image_size: 256
  hidden_dim: 386
  output_dim: 386
  depth: 10
  num_heads: 12
  mlp_dim: 386
  patch_size: 16
  projection_hidden_size: 386
  projection_layers: 4
training:
  learning_rate: 0.0007
  max_epochs: 512
  checkpoints_folder: "./models"
  gpus: 1
