random_seed: 42
data:
  image_folder: "/home/ilyabushmakin/Documents/Projects/DataStorage/kaggle_personal/ProjectDINODataset/images"
  batch_size: 8
  num_workers: 5
model:
  image_size: 256
  hidden_dim: 512
  output_dim: 512
  depth: 10
  num_heads: 8
  mlp_dim: 512
  patch_size: 16
  projection_hidden_size: 512
  projection_layers: 3
training:
  learning_rate: 0.0007
  max_epochs: 128
  checkpoints_folder: "./models"
  gpus: 1
